const express = require('express')
const bcrypt = require('bcrypt')
require('./db/mongoose')
const userRouter = require('../src/routers/user')
const toyRouter = require('../src/routers/toys')
const app = express()
const port = process.env.PORT
const cors = require('cors')
app.use(cors())
app.use(express.json())
app.use(userRouter)
app.use(toyRouter)
app.listen(3000,()=>{
    console.log('Server is up on port ' + 3000)
})